/* Derives the leaderboard's plausibility ceilings from the game's own tables,
   by driving the real `buildWave` at every depth and adding up the most score
   a wave could possibly pay. The alternative is hand-writing a ceiling and
   watching it drift the first time the roster gets retuned; this way the
   ceiling is generated from the same numbers the game plays by, and you
   regenerate it when you change them.

   Writes server/src/limits.js. Run with: node tools/gen-limits.mjs */
import fs from "fs";
import { load } from "../tests/harness.mjs";

const { d } = load();
const MAX_WAVE = 120;

/* Points come from the same places addScore() is called:
     normal kill      k.points + wave
     effigy / chaff   45 + wave
     boss             200 * tier
     heart on full hp 30
     wave cleared     wave * 25
   all multiplied by the depth's score factor. */
const PTS = {
  drifter: 10, harrier: 24, spitter: 18, diver: 14, splitter: 22,
  spawnling: 4, lancer: 26, warden: 34, seeder: 30, howler: 28,
  emplacer: 32, censer: 30,
};

/* Things the queue does not tell us about, counted generously on purpose.
   A splitter breaks into spawnlings, a seeder keeps producing, and the Gallery
   pays per effigy. This is a ceiling, not a model — it only has to sit above
   anything reachable, and being loose costs nothing because a cheated score is
   not 15% high, it is 50x high. */
const SPLIT_YIELD = 4;     // spawnlings per splitter, over-counted
const SEED_YIELD = 8;      // spawns per seeder over its life, over-counted
const HEARTS_PER_WAVE = 6; // every heart landing on a full bar, at 30 each

function waveMax(n, depthIndex) {
  const dif = d.DIFFICULTIES[depthIndex];
  d.state.wave = n;
  d.state.event = null;
  d.state.difficulty = depthIndex;
  d.buildWave(n);
  const q = d.queue.slice();

  let raw = 0;
  for (const kind of q) {
    if (kind === "boss") {
      // tier climbs with the run; be generous about how fast
      raw += 200 * Math.max(1, Math.ceil(n / 5));
    } else if (kind === "prime" || kind === "effigy") {
      raw += 45 + n;
    } else {
      raw += (PTS[kind] || 34) + n;
      if (kind === "splitter") raw += SPLIT_YIELD * (PTS.spawnling + n);
      if (kind === "seeder") raw += SEED_YIELD * (PTS.spawnling + n);
    }
  }
  raw += n * 25;                       // clearing the wave
  raw += HEARTS_PER_WAVE * 30;         // overflow hearts
  return { score: Math.round(raw * dif.score), spawns: q.length };
}

/* The time floor is the strongest invariant available, and it is the one a
   cheater almost never bothers to fake. Enemies cannot arrive faster than
   `spawnT` allows, so reaching wave W takes at least the sum of every spawn
   gap below it. A run claiming wave 40 in ninety seconds is not a good run. */
function spawnGapFrames(wave, burst) {
  return Math.max(burst ? 4 : 7, (burst ? 30 : 40) - wave * 2);
}

const table = d.DIFFICULTIES.map((dif, di) => {
  const score = [0];
  const frames = [0];
  let s = 0, f = 0;
  for (let n = 1; n <= MAX_WAVE; n++) {
    const w = waveMax(n, di);
    s += w.score;
    f += w.spawns * spawnGapFrames(n, dif.burst);
    score.push(s);
    frames.push(f);
  }
  return { id: dif.id, score, frames };
});

/* Headroom on the score ceiling. Upgrades, weapon stacking and a lucky
   Gallery all pay more than the naive sum, and a false rejection is far worse
   than a permissive one: it silently deletes a legitimate record and the
   player has no way to know why. */
const SLACK = 1.6;
/* Slack on the time floor goes the other way -- shave it, so an unusually
   fast legitimate run is never called a lie. */
const TIME_SLACK = 0.55;

const out = `/* GENERATED by tools/gen-limits.mjs -- do not edit by hand.
   Derived from the game's own DIFFICULTIES and buildWave tables. Regenerate
   whenever the roster, the point values or the depth multipliers change:

     node tools/gen-limits.mjs

   maxScore[depth][wave] is the most score that wave could possibly have paid,
   summed from wave 1, with ${SLACK}x headroom on top.
   minFrames[depth][wave] is the fewest frames it could have taken to get
   there, at ${TIME_SLACK} of the true spawn-gap floor. */

export const MAX_WAVE = ${MAX_WAVE};
export const DEPTHS = ${JSON.stringify(table.map((t) => t.id))};

export const LIMITS = {
${table.map((t) => `  ${t.id}: {
    maxScore: [${t.score.map((v) => Math.round(v * SLACK)).join(",")}],
    minFrames: [${t.frames.map((v) => Math.round(v * TIME_SLACK)).join(",")}],
  },`).join("\n")}
};
`;

fs.mkdirSync(new URL("../server/src/", import.meta.url), { recursive: true });
fs.writeFileSync(new URL("../server/src/limits.js", import.meta.url), out);

console.log("wrote server/src/limits.js");
for (const t of table) {
  const w = [10, 25, 50, 100];
  console.log("  " + t.id.padEnd(9),
    w.map((n) => `w${n}: <=${Math.round(t.score[n] * SLACK).toLocaleString()}`).join("  "));
}
